name                = "klaviyo-mcp-server-1"
main                = "src/index.js"         # keep pointing at the JS file
compatibility_date  = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[build.upload]
format = "modules"          # 👈 forces Module-Worker bundling
