toml<br>name = "klaviyo-mcp-server"<br>main = "src/index.ts" # or .js if you are using JavaScript<br>compatibility_date = "2024-12-01"<br>compatibility_flags = ["nodejs_compat"] # lets Node APIs like ‘crypto’ work<br>
