name               = "klaviyo-mcp-server-1"
main               = "src/index.js"          # or .ts if you convert later
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]      # keeps crypto, path, etc. working
